set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN B18 [get_ports RxD]
set_property IOSTANDARD LVCMOS33 [get_ports RxD]


#set_property PACKAGE_PIN U16 [get_ports {RxData[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {RxData[0]}]
#set_property PACKAGE_PIN E19 [get_ports {RxData[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {RxData[1]}]
#set_property PACKAGE_PIN U19 [get_ports {RxData[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {RxData[2]}]
#set_property PACKAGE_PIN V19 [get_ports {RxData[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {RxData[3]}]
#set_property PACKAGE_PIN W18 [get_ports {RxData[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {RxData[4]}]
#set_property PACKAGE_PIN U15 [get_ports {RxData[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {RxData[5]}]
#set_property PACKAGE_PIN U14 [get_ports {RxData[6]}]
#set_property OSTANDARD LVCMOS33 [get_ports {RxData[6]}]
#set_property PACKAGE_PIN V14 [get_ports {RxData[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {RxData[7]}]


set_property PACKAGE_PIN W4 [get_ports {en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en[0]}]
set_property PACKAGE_PIN V4 [get_ports {en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en[1]}]
set_property PACKAGE_PIN U4 [get_ports {en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en[2]}]
set_property PACKAGE_PIN U2 [get_ports {en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en[3]}]

set_property PACKAGE_PIN W7 [get_ports {LEDs[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[0]}]
set_property PACKAGE_PIN W6 [get_ports {LEDs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN U8 [get_ports {LEDs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN V8 [get_ports {LEDs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[3]}]
set_property PACKAGE_PIN U5 [get_ports {LEDs[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[4]}]
set_property PACKAGE_PIN V5 [get_ports {LEDs[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[5]}]
set_property PACKAGE_PIN U7 [get_ports {LEDs[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[6]}]
